
[stoneGen]

	[stoneGen.marble]
		#Veins per chunk
		#Default: 6
		#Range: 1 ~ 256
		perChunk = 6
		#Max size of vein
		#Default: 20
		#Range: 1 ~ 256
		maxVein = 20
		#Start height of veins
		#Default: 20
		#Range: 0 ~ 256
		start = 0
		#End height of veins
		#Default: 80
		#Range: 0 ~ 256
		end = 80
		#Is this stonegen option enabled
		enabled = true

	[stoneGen.basalt]
		#Veins per chunk
		#Default: 6
		#Range: 1 ~ 256
		perChunk = 6
		#Max size of vein
		#Default: 20
		#Range: 1 ~ 256
		maxVein = 20
		#Start height of veins
		#Default: 15
		#Range: 0 ~ 256
		start = 0
		#End height of veins
		#Default: 50
		#Range: 0 ~ 256
		end = 80
		#Is this stonegen option enabled
		enabled = true

	[stoneGen.limestone]
		#Veins per chunk
		#Default: 6
		#Range: 1 ~ 256
		perChunk = 6
		#Max size of vein
		#Default: 20
		#Range: 1 ~ 256
		maxVein = 20
		#Start height of veins
		#Default: 20
		#Range: 0 ~ 256
		start = 0
		#End height of veins
		#Default: 80
		#Range: 0 ~ 256
		end = 80
		#Is this stonegen option enabled
		enabled = true

